### Problem Statement 1:
Write a function so that the columns of the output matrix are powers of the input
vector.<br>
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br>
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [23]:
import numpy as np
list_input = []
increasing = bool

# defining function
def alexandre_theophile_vandermonde(x,order):
    N = x.size
    if order == True:
        return np.flip(np.column_stack([x**(N-1-i) for i in range(N)]), axis = 1)
    elif order == False:
        return np.column_stack([x**(N-1-i) for i in range(N)])

# taking input into a numpy array:
reply1 = input("Do you want to enter a number in the list? (y/n): ")
while reply1 == 'y':
    num = int(input("Enter the number: "))
    list_input.append(num)
    reply1 = input("Do you want to add some more numbers? (y/n): ")
list_input = np.array(list_input)
print(list_input)

# taking input for the order of the matrix
reply2 = input("Do you want the matrix in increasing order? (y/n): ")
if reply2 == 'y':
    increasing = True
else:
    increasing = False
print(increasing)

# execution of the function
alexandre_theophile_vandermonde(list_input, increasing)


Do you want to enter a number in the list? (y/n): y
Enter the number: 2
Do you want to add some more numbers? (y/n): y
Enter the number: 4
Do you want to add some more numbers? (y/n): y
Enter the number: 6
Do you want to add some more numbers? (y/n): y
Enter the number: 8
Do you want to add some more numbers? (y/n): y
Enter the number: 10
Do you want to add some more numbers? (y/n): n
[ 2  4  6  8 10]
Do you want the matrix in increasing order? (y/n): y
True


array([[    1,     2,     4,     8,    16],
       [    1,     4,    16,    64,   256],
       [    1,     6,    36,   216,  1296],
       [    1,     8,    64,   512,  4096],
       [    1,    10,   100,  1000, 10000]])

### Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:<br>
The moving average sequence has n-k+1 elements as shown below.<br>
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
<br>i 1 2 3 4 5 6 7 8 9 10
<br>===== == == == == == == == == == ==
<br>Input 10 20 30 40 50 60 70 80 90 100
<br>y1 25 = (10+20+30+40)/4
<br>y2 35 = (20+30+40+50)/4
<br>y3 45 = (30+40+50+60)/4
<br>y4 55 = (40+50+60+70)/4
<br>y5 65 = (50+60+70+80)/4
<br>y6 75 = (60+70+80+90)/4
<br>y7 85 = (70+80+90+100)/4
<br>Thus, the moving average sequence has n-k+1=10-4+1=7 values.
<br>
### Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
<br>Note: Solution submitted via github must contain all the detailed steps.

In [37]:
import numpy as np
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def movingaverage(a, n=3):
    # we use np.cumsum to get cumulative sum of the num
    asum = np.cumsum(a, dtype=float)
    # we are breaking the array as per desired number is 'n'
    # and substracting elements to get the desired result
    asum[n:] = asum[n:] - asum[:-n]
    return asum[n-1:]/n
a = np.array(dataset)
np.array(movingaverage(a,n=3)).round(3)


array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])